#!/usr/bin/env python3
from pathlib import Path
import json,re,pandas as pd
from docx import Document
from docx.shared import Inches,Pt
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'outputs/研究升级/Communications_Biology_v4';MC=ROOT/'outputs/研究升级/high_impact_v4/multicohort_osteoporosis_validation';HU=ROOT/'outputs/研究升级/high_impact_v4/human_only_sensitivity'
def para(d,start):
 a=[p for p in d.paragraphs if p.text.startswith(start)]
 if len(a)!=1: raise RuntimeError((start,len(a)))
 return a[0]
def replace(d,start,text): para(d,start).text=text
def insert_before(d,start,blocks):
 h=para(d,start)
 for style,text in blocks:
  p=d.add_paragraph(text,style=style);h._p.addprevious(p._p)
def table(d,headers,rows,font=6.5):
 t=d.add_table(rows=1,cols=len(headers));t.style='Table Grid'
 for j,h in enumerate(headers):t.rows[0].cells[j].text=str(h)
 for row in rows:
  c=t.add_row().cells
  for j,v in enumerate(row):c[j].text=str(v)
 for row in t.rows:
  for c in row.cells:
   for p in c.paragraphs:
    for x in p.runs:x.font.size=Pt(font)
 return t
def main():
 p=OUT/'Manuscript_Communications_Biology.docx';d=Document(p)
 abstract=('Matrix stiffness regulates mesenchymal stromal cells, but whether its transcriptomic effects generalize or relate to osteoporosis is unclear. We systematically identified seven public stiffness studies comprising 13 contrasts. No gene passed false-discovery-rate correction, and pooled pathway signals disappeared when each study was treated as the inference unit. Response magnitude nevertheless localized to human osteoblast-lineage programs, including a spatial program supported in six of seven studies by covariate-matched analysis. Removing two rat studies left the core result unchanged. Across three independent human osteoporosis cohorts, neither response magnitude, signed effects nor a fixed signature replicated in combined exact-permutation tests; a weak magnitude association appeared only in primary osteoblasts. Orthogonal tests using osteogenic states, mechanically perturbed chromatin accessibility and bone-mineral-density genetics were also negative. Public data therefore support context-dependent, distributed osteoblast-lineage mechanosensitivity without a universal stiffness signature or osteoporosis biomarker.')
 replace(d,'Matrix stiffness regulates mesenchymal stromal cells, but',abstract)
 replace(d,'Stiffness-response magnitude weakly tracks disease separation in multi-donor osteoblasts','Osteoporosis relevance is cohort-dependent rather than universal')
 insert_before(d,'Osteoporosis relevance is cohort-dependent rather than universal',[('Heading 2','Human-only sensitivity preserves the central conclusion'),('Normal','We repeated the stiffness meta-analysis after excluding rat GSE181512 and GSE310514 under a protocol frozen before result inspection. Among 12,757 genes represented in at least three of five human studies, none passed FDR correction. Human-only and seven-study pooled effects were strongly concordant (Spearman rho=0.810). Repeating the three disease-cohort tests with human-only meta z scores and a human-only fixed signature produced null equal-cohort results for response magnitude (P=0.199), direction (P=0.138) and signature transfer (P=0.0835). Thus, the absence of a universal program was not caused by cross-species synthesis.')])
 replace(d,'We next analyzed GSE156508','We tested disease relevance in three independent human cohorts with complete label-allocation inference: GSE156508 primary osteoblasts from six women with osteoporotic hip fracture and six women with severe osteoarthritis, GSE35958 cultured bone-marrow MSCs from five primary-osteoporosis cases and four age-matched controls, and GSE230665 femur tissue from 12 postmenopausal-osteoporosis cases and three controls [13,20,21]. Absolute stiffness meta z scores correlated weakly with absolute disease separation only in GSE156508 (rho=0.0254; one-sided exact P=0.0303). The corresponding results were null in GSE35958 (rho=0.00094; P=0.500) and reversed in GSE230665 (rho=-0.0110; P=0.703; Fig. 4a). An equal-cohort synthesis of standardized exact-null statistics was not significant (Monte Carlo P=0.259; 500,000 draws; Fig. 4b).')
 replace(d,'The association concerned response magnitude','Signed effects did not transfer in any cohort, and their combined exact-null test was null (P=0.254). The fixed 200-gene signature differed in GSE35958 (exact P=0.0238) but not GSE156508 (P=0.223) or GSE230665 (P=0.631); the cross-cohort synthesis was also null (P=0.095; Fig. 4c). GSE156508 leave-one-donor-out correlations were all positive, whereas the other cohorts were not deletion-stable. Because tissues, cell types and comparators differed, these results define context dependence rather than diagnostic performance.')
 cap=para(d,'Figure 4  Multi-donor primary osteoblast validation')
 cap.text='Figure 4  Multi-cohort osteoporosis validation. a, Observed absolute-effect correlations (orange) and 95% intervals of their complete label-allocation null distributions in three independent human cohorts. Exact one-sided P values are shown. b, Equal-cohort standardized statistic and its 500,000-draw combined null distribution. c, Exact two-sided P values for signed-effect and fixed-signature transfer; dashed line denotes P=0.05 without cross-cohort multiplicity adjustment. BM-MSC, bone-marrow mesenchymal stromal cell.';cap.runs[0].bold=True
 # Replace the picture immediately before the caption with the regenerated Figure 4.
 pic=cap._p.getprevious();pic.clear_content();from docx.text.paragraph import Paragraph
 pp=Paragraph(pic,cap._parent);pp.alignment=1;pp.add_run().add_picture(str(OUT/'Figure_4.png'),width=Inches(6.65))
 replace(d,'The multi-donor primary osteoblast analysis adds','Disease validation across three independent human cohorts sharpens the biological claim. The one positive absolute-effect test in primary osteoblasts did not generalize to MSCs or femur tissue, and no endpoint survived equal-cohort synthesis. This pattern is compatible with cell-state-specific distributed mechanosensitivity and incompatible with a stable cross-tissue osteoporosis biomarker. Exact label tests preserve donors as the experimental units and avoid treating thousands of correlated genes as independent observations.')
 replace(d,'This study is limited by small source studies','This study is limited by small source studies, heterogeneous processed data, incomplete matrix metadata and only seven independent stiffness series. The human-only sensitivity contained five studies and therefore had limited power, although its effect estimates agreed closely with the full model. Disease cohorts differed in cell source, platform, osteoporosis definition and comparator; GSE156508 used severe osteoarthritis rather than healthy bone, and GSE230665 had only three controls. The isolated GSE35958 signature result did not replicate across cohorts. GSE147390 contained one donor, and the ATAC perturbation contained two samples per group. These analyses establish neither causality, tissue material stiffness, clinical prediction nor a diagnostic biomarker.')
 replace(d,'GSE156508 normalized GPL16686 expression profiles','Three independent disease cohorts were analyzed with donor or participant labels as the inference unit [13,20,21]. GSE156508 comprised six osteoporotic-fracture and six severe-osteoarthritis primary osteoblast donors; GSE35958 comprised five primary-osteoporosis and four age-matched control BM-MSC donors; GSE230665 comprised 12 postmenopausal-osteoporosis and three control femur samples. The primary statistic in each cohort was Spearman correlation between absolute stiffness meta z and absolute Welch case-control t. All unique label allocations were enumerated (924, 126 and 455, respectively). Signed correlations and fixed-signature scores used two-sided exact tests. Cohort statistics were standardized against their exact nulls and averaged with equal weights; combined P values used 500,000 Monte Carlo draws from the three exact null distributions (seed 20260909). GSE35956 was excluded because it reused GSE35958 cases with younger controls, and GSE157322 because BMD group was fully confounded with ancestry.')
 insert_before(d,'Statistics and reproducibility',[
  ('Heading 2','Human-only sensitivity analysis'),
  ('Normal','Before inspecting results, we froze a species-sensitivity protocol that excluded rat GSE181512 and GSE310514. The same REML and modified Hartung-Knapp model was fitted to five human stiffness studies, retaining genes represented in at least three studies and controlling FDR across all eligible genes. Disease analyses were then repeated with a newly derived human-only 200-gene signature and the same exact allocation procedures. This analysis tested species dependence; it was not treated as an independent discovery analysis.')])
 replace(d,'Primary transcriptomic data are available','Primary stiffness transcriptomes are available from NCBI GEO under GSE193021, GSE181512, GSE226411, GSE288678, GSE55867, GSE255574 and GSE310514. Osteoblast and osteoporosis validations used GSE147390, GSE156508, GSE35958 and GSE230665. External datasets are GSE166824, GSE22011, GSE152708, GSE276529, GSE317531 and GSE287556. Human femoral single-cell data are GSE317069, spatial bone data GSE299207 and the eBMD GWAS GWAS Catalog GCST90726625 [9]. Search exports, screening decisions, exact null distributions, derived matrices, figure source data and executable code accompany this submission.')
 insert_before(d,'Acknowledgements', [('Normal','21. National Center for Biotechnology Information. Transcriptome profiling of femur tissue in postmenopausal osteoporosis. Gene Expression Omnibus GSE230665 (2023).')])
 d.save(p);print('abstract_words',len(re.findall(r"\b[\w-]+\b",abstract)))
def supp():
 p=OUT/'Supplementary_Information_Communications_Biology.docx';d=Document(p);m=pd.read_csv(MC/'cohort_results.csv');h=json.loads((HU/'human_only_sensitivity_summary.json').read_text())
 d.add_heading('Multi-cohort osteoporosis validation',1)
 table(d,['cohort','control/case','shared genes','absolute rho','exact P','signed rho','exact P','signature difference','exact P'],[[r.cohort,f'{r.n_control}/{r.n_case}',r.shared_genes,f'{r.abs_rho:.5f}',f'{r.abs_exact_one_sided_p:.5f}',f'{r.signed_rho:.5f}',f'{r.signed_exact_two_sided_p:.5f}',f'{r.signature_difference:.5f}',f'{r.signature_exact_two_sided_p:.5f}'] for r in m.itertuples()],5.3)
 d.add_paragraph('Supplementary Table 19  Complete label-allocation tests in three independent human disease cohorts. Absolute-effect tests were prespecified one-sided; signed and signature tests were two-sided.')
 table(d,['endpoint','equal-cohort statistic','Monte Carlo P','draws','alternative'],[[k,f"{v['equal_weight_mean_standardized_statistic']:.5f}",f"{v['monte_carlo_p']:.5f}",v['draws'],v['alternative']] for k,v in json.loads((MC/'multicohort_osteoporosis_validation_summary.json').read_text())['combined'].items()],6.2)
 d.add_paragraph('Supplementary Table 20  Cross-cohort synthesis. Each cohort contributed one standardized statistic, preventing the largest cohort or gene count from dominating inference.')
 ho=pd.read_csv(HU/'human_only_disease_results.csv')
 table(d,['cohort','shared genes','absolute rho','exact P','signed rho','exact P','signature difference','exact P'],[[r.cohort,r.shared_genes,f'{r.abs_rho:.5f}',f'{r.abs_exact_one_sided_p:.5f}',f'{r.signed_rho:.5f}',f'{r.signed_exact_two_sided_p:.5f}',f'{r.signature_difference:.5f}',f'{r.signature_exact_two_sided_p:.5f}'] for r in ho.itertuples()],5.5)
 d.add_paragraph(f"Supplementary Table 21  Human-only sensitivity. Five human stiffness studies yielded {h['genes_k_ge_3']:,} genes, zero FDR-significant genes and rho={h['full_vs_human_effect_spearman']:.3f} concordance with the seven-study effects. Combined P values were {h['combined']['abs']['p']:.3f}, {h['combined']['signed']['p']:.3f} and {h['combined']['signature']['p']:.3f} for absolute, signed and signature endpoints.")
 table(d,['candidate cohort','decision','reason'],[['GSE35956','Excluded','Reused GSE35958 osteoporosis cases and used younger controls; not independent.'],['GSE157322','Excluded','Low-BMD and high-BMD groups were fully confounded with ancestry.'],['GSE156508','Included','Independent donor-resolved primary osteoblast cohort; OA comparator retained as a limitation.'],['GSE35958','Included','Independent age-matched donor-resolved BM-MSC cohort.'],['GSE230665','Included','Independent femur cohort; only three controls retained as a limitation.']],6.0)
 d.add_paragraph('Supplementary Table 22  Independence and confounding audit for osteoporosis validation cohorts.')
 d.save(p)
def cover():
 p=OUT/'Cover_Letter_Communications_Biology.docx';d=Document(p)
 replace(d,'We challenged that interpretation','We challenged that interpretation with covariate-matched gene-set tests, study-unit inference, a frozen human-only sensitivity analysis and three independent donor- or participant-level osteoporosis cohorts. Removing rat studies left the central result unchanged. A weak response-magnitude association in primary osteoblasts did not reproduce in BM-MSCs or femur tissue, and equal-cohort exact-null synthesis was negative. Donor-resolved osteogenic states, mechanical-intervention ATAC-seq and eBMD statistics from 448,010 participants further bound the claim.')
 d.save(p)
if __name__=='__main__':main();supp();cover()
